force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Given Notice</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Do Not Use</fullName>
                <isActive>false</isActive>
                <label>Do Not Use</label>
            </value>
            <value>
                <fullName>Live Client</fullName>
                <isActive>false</isActive>
                <label>Live Client</label>
            </value>
            <value>
                <fullName>Live No Client</fullName>
                <isActive>false</isActive>
                <label>Live No Client</label>
            </value>
            <value>
                <fullName>Not Proceeding</fullName>
                <isActive>false</isActive>
                <label>Not Proceeding</label>
            </value>
            <value>
                <fullName>On Hold</fullName>
                <isActive>false</isActive>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>Potential (DD In Progress)</fullName>
                <isActive>false</isActive>
                <label>Potential (DD In Progress)</label>
            </value>
            <value>
                <fullName>Prospect (DD Complete)</fullName>
                <isActive>false</isActive>
                <label>Prospect (DD Complete)</label>
            </value>
            <value>
                <fullName>Transitioned</fullName>
                <isActive>false</isActive>
                <label>Transitioned</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initiator</fullName>
            </value>
            <value>
                <fullName>Decision-maker</fullName>
            </value>
            <value>
                <fullName>Contract Signatory</fullName>
            </value>
            <value>
                <fullName>Economic Buyer</fullName>
            </value>
            <value>
                <fullName>Champion</fullName>
            </value>
            <value>
                <fullName>Detractor</fullName>
            </value>
            <value>
                <fullName>Gatekeeper</fullName>
            </value>
            <value>
                <fullName>Influencer</fullName>
            </value>
            <value>
                <fullName>End-user</fullName>
            </value>
            <value>
                <fullName>Primary Billing Contact</fullName>
            </value>
            <value>
                <fullName>Additional Billing Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContactSelector.cls
public with sharing class ContactSelector {
    private static final String ADDITIONAL_BILLING_CONTACT_ROLE = 'Additional Billing Contact';
    private static final String PRIMARY_BILLING_CONTACT_ROLE = 'Primary Billing Contact';
    private static final String EXCLUDE_ACCOUNT_STATUS = 'Prospect';

    public static List<Contact> getContactsByAccountIds(List<Id> accountIds) {
        List<String> validRoles = new List<String>{ADDITIONAL_BILLING_CONTACT_ROLE, PRIMARY_BILLING_CONTACT_ROLE};
        return [
            SELECT 
                Id, 
                Account.Status__c, 
                Role__c,
                FirstName,
                LastName,
                Email,
                AccountId, 
                Account.Name, 
                Account.BillingStreet, 
                Account.BillingCountry, 
                Account.BillingCity, 
                Account.BillingState, 
                Account.BillingPostalCode, 
                Account.RecordType.DeveloperName,
                Account.Parent.Name
            FROM Contact 
            WHERE 
                AccountId IN :accountIds
                AND Role__c IN :validRoles
                AND Account.Status__c != :EXCLUDE_ACCOUNT_STATUS
            WITH SECURITY_ENFORCED
        ];
    }

    public static List<Contact> getAdditionalContacts(List<Id> accountIds) {
        return [
            SELECT 
                Id, 
                Account.Status__c, 
                Role__c,
                FirstName,
                LastName,
                Email
            FROM Contact 
            WHERE 
                AccountId IN :accountIds
                AND Role__c = :ADDITIONAL_BILLING_CONTACT_ROLE
                AND Account.Status__c != :EXCLUDE_ACCOUNT_STATUS
            WITH SECURITY_ENFORCED
        ];
    }
}